#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ll='ls -l'
alias grep='grep --color=auto'

# change bash prompt
PS1='\[\033[0;34m\]\u \W > \[\033[00m\]'

# use threading in make
export MAKEFLAGS='-j2'

# check sudo commands for aliases
alias sudo='sudo '

# alias for common grub commands
alias mkgrubcfgfile='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias mkgrubsa='sudo grub-mkstandalone -o /mnt/shared/bootfiles/boot.efi -d /usr/lib/grub/x86_64-efi -O x86_64-efi --compress=xz /boot/grub/grub.cfg'

# alias for cd commands
alias cu='cd ..'

# function for ecryptfs
mtecrypt() {
    ecryptfs-insert-wrapped-passphrase-into-keyring /home/katie/.ecryptfs/wrapped-passphrase
    mount -i /home/katie/important
}

getpassword() {
    mounted=0
    [ -e $HOME/important/pw/sprd ] || { mtecrypt; mounted=1; }
    pw=$(gawk -v arg="$1" 'index($0,arg) { print $2 }' $HOME/important/pw/sprd)
    [ -n "$pw" ] \
    && { \
        echo "$pw" | xclip -sel clipboard; \
        echo "Password copied!"; } \
    || { \
        echo "Password for $1 not found..."; }
    [ "$mounted" -eq "1" ] && { echo "Unmounting partition..."; sleep 3; umount $HOME/important; }
}

getquestion() {
    mounted=0
    [ -e $HOME/important/pw/qus ] || { mtecrypt; mounted=1; }
    pw=$(gawk -v arg="$1" 'index($0,arg) { print $NF }' $HOME/important/pw/qus)
    [ -n "$pw" ] \
    && { \
        echo "$pw" | xclip -sel clipboard; \
        echo "Answer copied!"; } \
    || { \
        echo "Answer for $1 not found..."; }
    [ "$mounted" -eq "1" ] && { echo "Unmounting partition..."; sleep 3; umount $HOME/important; }
}

mkgrubcfg() {
    cp /mnt/shared/bootfiles/boot.efi /mnt/shared/bootfiles/boot.efi.old
    mkgrubcfgfile && \
    mkgrubsa && \
    sudo mount /mnt/efi && \
    sudo cp -v /mnt/shared/bootfiles/boot.efi /mnt/efi/System/Library/CoreServices/ &&
    sudo umount /mnt/efi
}

# Function to fix natural scrolling and tap-to-click in libinput, which seems
# to crash and reset randomly
fix-libinput-config() {
    # Fix tap-to-click
    xinput set-prop 11 289 1

    # Fix natural scrolling
    xinput set-prop 11 299 1
}


export EDITOR=vim

# export gopath
export GOPATH=$HOME/gopath
export PATH=$GOPATH:$GOPATH/bin:$PATH

# latex path
export LATEXPATH=/usr/local/texlive/2016/bin/x86_64-linux
export PATH=$LATEXPATH:$PATH
export MANPATH=/usr/local/texlive/2016/texmf-dist/doc/man:$MANPATH
export INFOPATH=/usr/local/texlive/2016/texmf-dist/doc/info:$INFOPATH

# Solarized colors in console
source ~/linux-config/custom-config/solarized_dark

# visual bell
set bell-style visible

# The next line updates PATH for the Google Cloud SDK.
if [ -f /home/katie/Downloads/google-cloud-sdk/path.bash.inc ]; then
  source '/home/katie/Downloads/google-cloud-sdk/path.bash.inc'
fi

# alias for pacman commands
alias pacup='pacman -Suy'
alias pacget='pacman -S'
alias pacdel='pacman -Runs'

# alias to open pdfs
alias opdf='ds qpdfview'

# The next line enables shell command completion for gcloud.
if [ -f /home/katie/Downloads/google-cloud-sdk/completion.bash.inc ]; then
  source '/home/katie/Downloads/google-cloud-sdk/completion.bash.inc'
fi

# Source ssh_find_agent script and start ssh-agent if not running
. ~/dotfiles/scripts/ssh-find-agent/ssh-find-agent.sh
ssh-find-agent -a || eval $(ssh-agent) > /dev/null
