#!/bin/bash
#
# Example config file for cdm(1).
# Values set here is the default as in cdm(1).

# List of programs, commands with whitespaces should be quoted or escaped.
# If unset, all sessions in /etc/X11/Sessions or /usr/share/xsessions are
# offered as choices.
#
# (An example:)
binlist=(
   '/home/katie/.xinit_deepin'
   '/home/katie/.xinit_lxqt'
   '/bin/bash --login'             # or just execute your shell,
   '/usr/bin/reboot'								# or go to a submenu :)
   '/usr/bin/shutdown'							
# or go to a submenu :)
#   '/usr/bin/cdm ~/.submenu.cdmrc' # or go to a submenu :)
)

# List all program display names, one-by-one matched with $binlist.
# Names with whitespaces should be quoted or escaped.
#
# (Continued example:)
namelist=(Deepin LXQT Shell reboot shutdown )

# Type of the programs, one-by-one matched with $binlist.
# `C' for *C*onsole programs, which would be `exec'ed.
# `X' for *X* programs, which would be run with cdm-xlaunch(1).
#
# (Continued example:)
flaglist=(X X C C C)

# Style for the cdm dialog, which is printed with dialog(1).
# Default to unset, causing dialog(1) to use the system wide default.
# See /usr/share/doc/cdm/themes for some nice choices.
dialogrc=/usr/share/cdm/themes/blackandwhite

# Index of the first item in the menu.
countfrom=0

# Set default display.
display=0

# Should cdm(1) stick to the specified display?
locktty=no

# Additional arguments to pass to X server, which is usually called as:
#   /usr/bin/X :$display "${serverargs[@]}" vt$((xtty+display))
# Arguments with whitespaces should be quoted or escaped.
serverargs=(-keeptty -nolisten tcp)
